name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create a folder named `directus-extension-bizprint-sign`
        run: mkdir -p directus-extension-bizprint-sign

      - name: Copy dist folder to `directus-extension-bizprint-sign`
        run: cp -r dist directus-extension-bizprint-sign

      - name: Copy package.json to `directus-extension-bizprint-sign`
        run: cp package.json directus-extension-bizprint-sign

      - name: Archive directus-extension-bizprint-sign
        run: zip -r directus-extension-bizprint-sign.zip directus-extension-bizprint-sign

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./directus-extension-bizprint-sign.zip
          asset_name: directus-extension-bizprint-sign.zip
          asset_content_type: application/zip